package controller;

import javafx.fxml.FXML;

import javafx.event.ActionEvent;

public class InicioSesionController {

	// Event Listener on Button.onAction
	@FXML
	public void botonlogin(ActionEvent event) {
		// TODO Autogenerated
	}
}
